- pseudocode/ibrahim-aljarad.md
added my pseudocode to your files
> this is my pseudocode

- pseudocode/betul-erkoc.md
> betul's pseudocode is added

- pseudocode/MAjd_Ajroudi.md
- pseudocode/Majd_Ajroudi.md
> added majd's pseudocode

- pseudocode/knar_gocer.md
Added the pseudocode for boiling water.
> Added the pseudocode of my group

- class2/Knar/index.html
- pseudocode/knar_gocer.md
> My web page

- class2/Luey-A/index.html
- pseudocode/Luey-Ahmad.md
I added my pseudocode file and my web page. It is very important information, please accept my pull request :).
> My first Pull request

- class2/ola ouso/index.html
- pseudocode/ola.md
> finally my pseudo code

- class2/abdullatif/index.html
- pseudocode/abdullatif.md
> my personal data

- pseudocode/Yaman-Sammani-bolling-water.md
Add Yaman Sammani Bowling water file
> Add Yaman Sammani Pseudocode

- class5/Ihab-Luey/index.js
> jschallenge0 ihab-sensei Luey-A

- class6/Jennet-Abdullatif/index.js
Please accept my pull request :)
> jschallenge1 jennethydyrova abdullatifsalih

- class6/Gizem-Ola/index.js
> jschallenge1 gizemcdeniz olaouso

- class7/bertac-yaman/index.js
Added index.js file which contains the challenges.
> strings-arrays-challenges bertacsevercan YamanSammani

- class7/Tarkan-Mohammed/strings-arrays-challenges.js
> strings-arrays-challenges tmansuroglu mohammad-jundi

- class7/Zeynep - Ahmad/index.js
> strings-arrays-challenges senzeynep ahmadaljalmoud

- class6/ibrahim-knar/app.js
js challenge added please check
> jschallenge1 ibrahimaljarad knargocer

- class7/Ihab-Khaldoon/index.js
> strings-arrays-challenges ihab-sensei khaldoon9kh

- class7/ibrahim-luey/app.js
please check our challenge if it done.
> strings-arrays-challenges ibrahimaljarad luey-A

- class9/mad-libs-basic tmansuroglu betulerkoc/index.html
- class9/mad-libs-basic tmansuroglu betulerkoc/script.js
> mad-libs-basic tmansuroglu betulerkoc

- class9/bertac-fadime/index.html
- class9/bertac-fadime/script.js
> mad-libs-basic bertacsevercan fadime94

- class8/Sule-Bertac/index.html
- class8/Sule-Bertac/index.js
- class8/Sule-Bertac/style.css
Please accept our pull request.
> events-calculator-challenge ssinikoglu bertacsevercan

- class9/ibrahim-cihan/app.js
please check our exercise  code.
> mad-libs-basic ibrahimaljarad cuyjur

- class8/Gizem-Knar/index.html
- class8/Gizem-Knar/script.js
Added the files for the calculator challenge
> events-calculator-challenge knargocer gizemcdeniz

- class9/Mohammad-Knar/index.html
- class9/Mohammad-Knar/script.js
- class9/Mohammad-Knar/style.css
Added mad libs files of our group
> mad-libs-basic knargocer mohammad-jundi

- class9/Sule-Majd/index.html
- class9/Sule-Majd/index.js
Please accept our pull request.
> mad-libs-basic ssinikoglu majdajroudi

- class8/Jennet-Khaldoon-Zeynep/index.js
> events-calculator-challenge jennethydyrova khaldoon9kh senzeynep

- object-exercises/object-exercises.js
> object-exercises

- class11/github-fetch-exercise-tmansuroglu-ahmadaljalmoud/index.html
- class11/github-fetch-exercise-tmansuroglu-ahmadaljalmoud/script.js
Some variable names are not good and there might be some indentation inaccuracies. But functionality is okay . Like you said before we will spend our time on madlibz project instead of improving this.
Please accept our request.
> github-fetch-exercise-tmansuroglu-ahmadaljalmoud

- class11/ibrahim-mohammad/index.js
> github-fetch-exercise ibrahimaljarad mohammad-jundi

- madlibz/ibrahimaljarad-cuygur/do-not-touch.js
- madlibz/ibrahimaljarad-cuygur/index.html
- madlibz/ibrahimaljarad-cuygur/madlibs.js
- madlibz/ibrahimaljarad-cuygur/story.txt
- madlibz/ibrahimaljarad-cuygur/style.css
please check our project added
> madlibz ibrahimaljarad cuygur

- minesweeper/Tarkan-Ray/index.js
> minesweeper tmansuroglu raycodes-2020
